name: Crypto Price Alerts

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Price Alert Check
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}  # Store your API URL in GitHub Secrets
          EMAIL_USER: ${{ secrets.EMAIL_USER }}  # SMTP email sender
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}  # SMTP password
        run: |
          python check_alerts.py  # This script runs check_price_drops()
